### ISSUE TITLE
[ISSUE] discord broke the oled theme

### ISSUE THREAD

**Issue by blankexistence** [dimdenGD/discord-oled-theme#16]
### request

my g, this oled theme needs to make a come back and look exactly like last time🙏 
it would be nice to see a better, well-optimised shadcn/ui variant of this oled theme you made that adapts the new discord ui, but that's just asking for extra - no need to do this unless ur interested in how it'd look

### description
discord broke custom css themes once more
although i do respect discord for going with the shadcn/ui makeover and all, but it just isn't up to scratch

like wtf is that text area / message bar???? 💀💀💀 

### screenshots

![Image](https://github.com/user-attachments/assets/6331072d-59ec-48ac-a048-9973ee328296)

#### Extra info:
i use vencord instead of betterdiscord but what difference does that make anyways?

**Comment by Tricked-dev** [comment]
i did a best effort update to amoled again to the new ui skin feel free to make prs and stuff to fix other parts this just changes the chat related stuff to be amoled again

https://github.com/Tricked-dev/amoled-new-discord-theme/blob/master/theme.css

**Comment by blankexistence** [comment]
these changes seem to apply good enough changes:

```css
.members_c8ffbb {
  width: var(--custom-member-list-width);
  padding: 0 0 20px;
  flex: 0 0 auto;
  height: auto;
  background: var(--background-secondary);
}

.container_c8ffbb {
  display: flex;
  flex-direction: column;
  background: var(--background-secondary);
  height: 100%;
}

.visual-refresh .channelTextArea_f75fb0 {
  background: var(--background-secondary);
}

#channels,
[aria-label="Private channels"] > [data-jump-section="global"] {
  background-color: var(--background-secondary);
}

.visual-refresh .privateChannels__35e86 {
  background: var(--background-secondary);
}

.lookFilled__201d5.colorPrimary__201d5 {
  color: var(--button-secondary-text);
  background-color: var(--background-secondary);
}

div > section[aria-label="User area"].panels_c48ade {
  background-color: var(--background-secondary);
}

.visual-refresh .panel__5dec7 {
  background-color: var(--background-secondary);
}
```
